/*
	FileManager.h

	Providing I/O services for the Sudoku class

	It always accepts file path and the sudoku object. It writes the sudoku Table to the file and resets the statistics.
	Whenever a sudoku is written to a file the number of rounds is incremented, and the other paramathers are set back to 0.
	There are 2 read functions, one is to read from the first file provided with argv, and the other reads from a file when
	a user is expected to provide their solution of the sudokuTable.


	Author: Marija Parezanin
	Date: 18.12.2023
	email: marija.parezanin@mensa.ba
	F: FTN SIIT, SV1/2022

*/
#pragma once
#include "Sudoku.h"

namespace fms {
	//load the sudoku grid to the passed sudoku
	void readFile(Sudoku& s, std::string filePath);

	//optional incGameNum because when the game is generated by the program, the setup and the solution both get written, but
	//the number of games should increase only once
	void writeFile(Sudoku& s, std::string filePath, bool incGameNum = true);

	//writes a line to just seperate the look of rounds in solutions file
	void writeEndOfRound(std::string filePath, int gameRound);


}